# Site settings
title: Linh Bun
email: lbun@ucsc.edu
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
url: "http://bunlinh80.github.io" # the base hostname & protocol for your site
twitter_username: LinhBun9 
github_username:  bunlinh80
permalink: /:year/:month/:title.html

# Build settings
markdown: kramdown
exclude: ['*.Rmd']
