---
title: "Plotting background data for groups with ggplot2"
author: "Linh Bun"
date: '2017-09-20'
categories: ["R"]
tags: ["R Markdown", "plot", "regression"]
output: 
  html_document:
    toc: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Plotting

```{r}
library("ggplot2")
suppressMessages(library("tidyverse"))
library("hrbrthemes")
library("ggthemes")
```

```{r, dpi=300}
ggplot(iris, aes(x = Sepal.Width)) +
    geom_histogram()
```

```{r, dpi=300}
ggplot(iris, aes(x = Sepal.Width, fill = Species)) +
    geom_histogram() +
    theme_minimal()
```

```{r, dpi=300}
ggplot(iris, aes(x = Sepal.Width)) +
    geom_histogram() +
    facet_wrap(~ Species) +
    theme_minimal()
```

## General Idea
```{r, eval=FALSE, include=TRUE}
ggplot(data = full_data_frame,
       mapping = aes(...)) +
    geom_*(data = data_frame_without_grouping_var,
           mapping = aes(...),
           colour/fill = "neutral_color") +
    geom_*() +
    facet_wrap(~ grouping_var) +
    theme_*()
```

### Alternative
```{r, eval=FALSE, include=TRUE}
ggplot(data = full_data_frame) +
    geom_*(data = data_frame_without_grouping_var,
           mapping = aes(...),
           colour/fill = "neutral_color") +
    geom_*(mapping = aes(..., group = grouping_var)) +
    facet_wrap(~ grouping_var) +
    theme_minimal()
```

```{r data}
d <- iris        # Full data set
d_bg <- d[, -5]  # Background Data - full without the 5th column (Species)
```

```{r}
head(d)
tail(d)
```

```{r}
d
```

```{r}
str(d)
```

```{r, dpi=300}
ggplot(data = d,
       mapping = aes(x = Sepal.Width)) +
    geom_histogram(data = d_bg,
                   fill = "grey") +
    geom_histogram() +
    facet_wrap(~ Species)
```

```{r, dpi=300}
ggplot(data = d,
       mapping = aes(x = Sepal.Width, fill = Species)) +
    geom_histogram(data = d_bg,
                   fill = "grey",
                   alpha = 0.5) +
    geom_histogram(color = "black") +
    facet_wrap(~ Species) +
    guides(fill = FALSE) +
    theme_minimal()
```

```{r, dpi=300}
# d <- iris        # Full data set
# d_bg <- d[, -5]  # Background Data - full without the 5th column (Species)

ggplot(d, aes(x = Sepal.Width, fill = Species)) +
  geom_histogram(data = d_bg, fill = "grey", alpha = .5) +
  geom_histogram(colour = "black") +
  facet_wrap(~ Species) +
  guides(fill = FALSE) +  # to remove the legend
  theme_bw()              # for clean look overall
```

## point example
```{r, dpi=300}
ggplot(data = d,
       mapping = aes(x = Sepal.Width, y = Sepal.Length)) +
    geom_point(data = d_bg,
               color = "grey",
               alpha = 0.5) +
    geom_point() +
    facet_wrap(~ Species) +
    theme_minimal()
```

```{r, dpi=300}
ggplot(d, aes(x = Sepal.Width, y = Sepal.Length)) +
  geom_point(data = d_bg, colour = "grey") +
  geom_point() + 
  facet_wrap(~ Species)
```

```{r, dpi=300}
ggplot(data = d,
       mapping = aes(x = Sepal.Width, y = Sepal.Length, color = Species)) +
    geom_point(data = d_bg,
               color = "grey",
               alpha = 0.5) +
    geom_point() +
    facet_wrap(~ Species) +
    guides(color = FALSE) +
    theme_minimal()
```

```{r, dpi=300}
ggplot(d, aes(x = Sepal.Width, y = Sepal.Length, colour = Species)) +
  geom_point(data = d_bg, colour = "grey", alpha = .2) +
  geom_point() + 
  facet_wrap(~ Species) +
  guides(colour = FALSE) +
  theme_bw()
```

## more example
```{r, dpi=300}
library("nycflights13")
library(dplyr)

usa_map <- map_data("usa")

airports <- read.csv("https://raw.githubusercontent.com/jpatokal/openflights/master/data/airports.dat", stringsAsFactors = FALSE, header = FALSE)
airports <- airports[, c(5, 7, 8)]
names(airports) <- c("code", "lat", "long")
orig <- airports %>% dplyr::rename(origin = code, long_o = long, lat_o = lat)
dest <- airports %>% dplyr::rename(dest = code, long_d = long, lat_d = lat)

d <- flights %>%
       left_join(orig) %>% 
       left_join(dest) %>% 
       filter(carrier %in% c("AS", "F9", "OO", "YV", "VX", "FL"))

d_bg <- d %>% select(-carrier)

ggplot(d) +
  geom_polygon(data = usa_map, aes(long, lat, group = region)) +
  geom_segment(data = d_bg, colour = "grey", alpha = .7,
               aes(x = long_o, y = lat_o,
                   xend = long_d, yend = lat_d)) +
  geom_segment(aes(x = long_o, y = lat_o,
                   xend = long_d, yend = lat_d,
                   colour = carrier)) +
  facet_wrap(~ carrier) +
  guides(colour = FALSE) +
  theme_bw()
```

### alternative
```{r, dpi=300}
ggplot(d) +
  geom_polygon(data = usa_map, aes(long, lat, group = region)) +
  geom_segment(data = d_bg, colour = "grey", alpha = .7,
               aes(x = long_o, y = lat_o,
                   xend = long_d, yend = lat_d)) +
  geom_segment(aes(x = long_o, y = lat_o,
                   xend = long_d, yend = lat_d,
                   colour = carrier)) +
  facet_wrap(~ carrier) +
  guides(colour = FALSE) +
  theme_minimal()
```

